// Contenido bilingüe ES / EN. El comprador objetivo es mayoritariamente extranjero (UK, Benelux, nórdicos).

export const PRICE_FINISHED = '1.590.000 €'

export const content = {
  es: {
    nav: { concept: 'Concepto', villas: 'Villas', gallery: 'Galería', location: 'Ubicación', cta: 'Dossier privado' },
    hero: {
      eyebrow: 'La Cala Golf · Mijas Costa · Costa del Sol',
      title1: 'Luxury Golf',
      title2: 'Collection',
      lead: '10 villas de lujo independientes, con putting green privado, en el corazón de La Cala Golf. Fase 1: solo 5 unidades.',
      cta: 'Recibir dossier y precios',
      cta2: 'Ver las villas',
      badge: 'Villa I · Fase final de obra',
      badgeSub: 'Visite la obra en persona',
      scroll: 'Descubrir',
    },
    stats: [
      { n: '10', l: 'Villas exclusivas' },
      { n: '1.650', u: 'm²', l: 'Parcela máxima' },
      { n: '4', l: 'Dormitorios' },
      { n: '2', u: 'min', l: 'A La Cala Golf' },
      { n: '30', u: 'min', l: 'Aeropuerto de Málaga' },
    ],
    concept: {
      eyebrow: 'Un nuevo paradigma residencial',
      title: 'No es una promoción. Es un enclave de vida privilegiado.',
      text: 'Nace un concepto exclusivo en el corazón de La Cala Golf: un conjunto limitado de 10 villas de lujo independientes, en una calle privada sin salida y de acceso restringido a residentes. El Master Plan sigue la topografía natural del terreno, logrando el equilibrio perfecto entre comunidad y privacidad absoluta.',
      features: [
        { t: 'Vistas inigualables', d: 'Orientación Norte-Sur estudiada para aprovechar la luz natural y las panorámicas a la sierra y al pueblo de Mijas.' },
        { t: 'Interior · Exterior', d: 'Terrazas cubiertas y descubiertas que crean una conexión fluida entre la casa, la piscina y el jardín.' },
        { t: 'Para amantes del golf', d: 'Espacio diseñado para instalar un putting green privado de aproximadamente 50 m² en su propia parcela.' },
        { t: 'Su resort privado', d: 'Calle privada, acceso restringido y parcelas de gran escala: la sensación de un resort, con la intimidad de su casa.' },
      ],
    },
    finished: {
      eyebrow: 'Estado actual · Inversión tangible',
      title: 'La primera villa ya está levantada.',
      text: 'Mientras otras promociones solo pueden enseñar renders, aquí la Villa I se encuentra en su fase final de construcción. Puede visitar la obra, recorrer la parcela, comprobar las vistas y ver los materiales reales antes de decidir. La prueba de que el proyecto avanza, con precio cerrado desde el primer día.',
      price: 'Villa I · Fase final de obra',
      priceNote: 'Precio de venta',
      facts: [
        ['Parcela', '1.120 m²'],
        ['Construida', '280 m² + terrazas'],
        ['Plantas', '3 niveles'],
        ['Dormitorios', '4 suites'],
        ['Garaje', 'Doble'],
        ['Piscina', 'Infinity 11 × 3 m'],
      ],
      cta: 'Solicitar visita a la obra',
    },
    villas: {
      eyebrow: 'Tres tipologías · Un estándar de excelencia',
      title: 'Elija la villa que encaja con su forma de vivir',
      text: 'Construidas con materiales premium y acabados de alta gama, cada propiedad es una obra de arquitectura contemporánea. Cuatro villas de la Fase 1 se venden sobre plano, con pagos por fases durante la construcción.',
      items: [
        {
          id: 'villa-1', n: 'Villa I', name: 'El Inicio de la Excelencia', tag: 'En construcción', img: '/img/Contra_frente_III.jpg',
          specs: [['Parcela', '1.120 m²'], ['Dormitorios', '4 suites'], ['Unidades', '1']],
          d: 'La primera villa de la colección, actualmente en fase de construcción. Incluye un salón de usos múltiples ideal para gimnasio privado, sala de cine o zona de juegos, y está orientada para maximizar las vistas panorámicas, con espacio exclusivo para un putting green de golf privado.',
          price: PRICE_FINISHED,
        },
        {
          id: 'villa-2', n: 'Villa II', name: 'Diseño y Amplitud Familiar', tag: 'Sobre plano', img: '/img/Lateral_II.jpg',
          specs: [['Parcela', '1.130 m²'], ['Dorm. / Baños', '4 / 5'], ['Unidades', '2']],
          d: 'Dos unidades disponibles en la Etapa 1, con acceso privado. Cuatro dormitorios y cinco baños completos que garantizan privacidad a cada habitante e invitado, y un gran salón de usos múltiples integrable a un estilo de vida moderno.',
          price: null,
        },
        {
          id: 'villa-3', n: 'Villa III', name: 'El Refugio de la Sierra', tag: 'Sobre plano', img: '/img/FachadaII.jpg',
          specs: [['Parcela', '1.650 m²'], ['Dorm. / Baños', '4 / 5'], ['Unidades', '2']],
          d: 'Dos unidades de máxima amplitud en la Etapa 1, sobre la parcela más extensa de la colección. Vistas plenas a la sierra, acceso privado y espacio exclusivo para instalar un putting green de golf privado.',
          price: null,
        },
      ],
      priceOnRequest: 'Precio bajo solicitud',
      cardCta: 'Ver planos y precio',
      units: 'Fase 1 · 5 villas',
    },
    gallery: {
      eyebrow: 'Un diseño pensado para el bienestar',
      title: 'Espacios que se viven, luz que se siente',
      items: [
        { src: '/img/salon-b.jpg', c: 'Salón con salida a terraza panorámica' },
        { src: '/img/cocina-madera.jpg', c: 'Cocina Schmidt abierta, con vistas a Mijas' },
        { src: '/img/Terraza.jpg', c: 'Terraza cubierta y piscina privada' },
        { src: '/img/Dormitorio.jpg', c: 'Dormitorio principal con terraza' },
        { src: '/img/Vestidor_II.jpg', c: 'Vestidor en suite' },
        { src: '/img/Gimnasio.jpg', c: 'Sala multiusos: gimnasio privado' },
        { src: '/img/Estar.jpg', c: 'Salón-comedor con salida a la terraza' },
        { src: '/img/salon-a.jpg', c: 'Zona de estar' },
      ],
      disclaimer: 'Imágenes recreadas digitalmente sin valor contractual. Mobiliario y decoración no incluidos.',
    },
    floors: {
      eyebrow: 'Tres plantas, infinitas posibilidades',
      items: [
        { t: 'Planta alta', d: 'Dormitorio principal en suite con vestidor, dos dormitorios adicionales, baño completo y terrazas privadas.' },
        { t: 'Planta baja', d: 'Salón-comedor diáfano, cocina Schmidt con isla central, aseo de cortesía, terrazas, zona chill-out semicubierta, barbacoa y piscina infinity de 11 × 3 m.' },
        { t: 'Planta sótano', d: 'Garaje doble con punto de carga para vehículo eléctrico, gran espacio diáfano con luz natural y baño completo (gimnasio, cine o cuarto dormitorio), lavadero, cuarto técnico y preinstalación de ascensor.' },
      ],
    },
    video: {
      line: 'Imagine despertar cada mañana en su refugio privado, donde el lujo se encuentra con la serenidad.',
      sub: 'Sobrevuelo · La Cala Golf',
    },
    location: {
      eyebrow: 'Cala Golf · Costa del Sol',
      title: 'Su oasis de tranquilidad en el corazón de la Costa del Sol',
      text: 'La Cala Golf es mucho más que una prestigiosa zona residencial: es un estilo de vida que combina tranquilidad, lujo y naturaleza. A 5 minutos de la autovía y a mitad de camino entre Málaga y Marbella, con sol 320 días al año y comunidad internacional consolidada.',
      groups: [
        { t: 'Golf', items: [['La Cala Golf', '2 min'], ['Mijas Golf', '14 min'], ['Santana Golf', '19 min']] },
        { t: 'Costa', items: [['La Cala de Mijas', '11 min'], ['Marbella', '20 min'], ['Fuengirola', '24 min']] },
        { t: 'Día a día', items: [['Supermercados', '8 min'], ['Farmacia', '12 min'], ['Hospital', '12 min']] },
        { t: 'Conexiones', items: [['Málaga · AVE · Aeropuerto', '30 min'], ['Gibraltar', '90 min']] },
      ],
      golf: {
        eyebrow: 'A dos minutos',
        t: 'Uno de los campos de golf más importantes de la Costa del Sol, a dos minutos de su puerta',
        d: 'La Cala Golf está prácticamente a la vuelta de la esquina: dos minutos en coche. Un referente internacional que marca el carácter de todo el entorno y que puede prolongar dentro de su propia parcela con un putting green privado de unos 50 m².',
      },
      map: {
        t: 'Cómo llegar',
        d: 'Calle Lagar de La Cala Golf · La Cala Golf, Mijas Costa (Málaga)',
        cta: 'Abrir en Google Maps',
      },
    },
    quality: {
      eyebrow: 'Memoria de calidades',
      title: 'Calidad que se demuestra, no solo se promete',
      items: [
        'Suelo radiante en toda la vivienda, con control por estancias',
        'Aerotermia Mitsubishi para climatización y agua caliente',
        'Climatización por conductos con zonificación Airzone',
        'Cocina Schmidt con isla central integrada',
        'Electrodomésticos Bosch integrados',
        'Porcelánico rectificado Cristacer Lloret Beige 90 × 90',
        'Baños revestidos y sanitarios Porcelanosa',
        'Carpintería exterior Strugal con rotura de puente térmico',
        'Doble acristalamiento con cámara de aire y protección UV',
        'Barandillas de vidrio laminado 8+8 con anclaje oculto',
        'Piscina infinity de 11 × 3 m con vaso de compensación',
        'Videoportero, alarma y clima zonificado',
        'Punto de carga para vehículo eléctrico',
        'Preinstalación de ascensor para las tres plantas',
      ],
      more: 'Descargue la memoria de calidades completa',
    },
    gated: {
      eyebrow: 'Acceso privado',
      title: 'Toda la información, en un solo dossier',
      text: 'Responda a 3 preguntas rápidas y reciba al instante la documentación completa del proyecto. Un asesor le contactará en su idioma para resolver cualquier duda, sin compromiso.',
      items: [
        ['Dossier completo', 'Renders, distribución y entorno'],
        ['Planos de venta', 'Las tres tipologías con superficies'],
        ['Memoria de calidades', 'Acabados y especificaciones técnicas'],
        ['Precios y plan de pagos', 'Disponibilidad actualizada Fase 1'],
      ],
      cta: 'Desbloquear dossier',
      time: 'Menos de 30 segundos',
    },
    process: {
      eyebrow: 'Comprar desde el extranjero, sin sorpresas',
      title: 'Un proceso claro, acompañado en cada paso',
      steps: [
        { t: 'Videollamada privada', d: 'Revisamos planos, vistas, precios y plan de pagos desde su casa.' },
        { t: 'Visita a la Costa del Sol', d: 'Recorra la villa terminada, la parcela y el entorno de La Cala Golf.' },
        { t: 'Reserva y due diligence', d: 'Documentación clara y coordinación con su abogado o asesor fiscal.' },
        { t: 'Construcción y entrega', d: 'Pagos por hitos e informes periódicos con fotos y vídeo de la obra.' },
      ],
    },
    final: {
      title: 'Haga realidad su vida en la Costa del Sol',
      text: 'Solo 5 villas en la Fase 1. Reciba hoy el dossier privado y reserve su visita.',
      cta: 'Quiero el dossier',
    },
    footer: {
      promoted: 'Promueve · Promoted by',
      legal: 'Aviso legal', privacy: 'Política de privacidad', cookies: 'Política de cookies',
      disclaimer: 'Todas las imágenes son recreaciones virtuales sin valor contractual. Mobiliario, vegetación y vehículos no forman parte de la oferta. La promotora Fusión +34 by Alternativa Málaga se reserva el derecho de efectuar modificaciones por requisitos técnicos, comerciales o legales, sin que impliquen una disminución de la calidad. Superficies aproximadas.',
    },
    sticky: 'Dossier y precios',
    wizard: {
      close: 'Cerrar',
      back: 'Atrás',
      next: 'Continuar',
      submit: 'Recibir dossier',
      sending: 'Enviando…',
      step: 'Paso',
      of: 'de',
      intro: 'Dossier privado · Luxury Golf Collection',
      q: {
        budget: { t: '¿Cuál es su presupuesto aproximado?', o: { lt1: 'Menos de 1 millón €', '1to15': 'Entre 1 y 1,5 millones €', gt15: 'Más de 1,5 millones €' } },
        location: { t: '¿Se encuentra actualmente en la Costa del Sol?', o: { yes: 'Sí, estoy aquí', no: 'No', soon: 'Planeo visitarla pronto' } },
        timing: { t: '¿Busca una villa para vivir pronto o a medio plazo?', o: { soon: 'Para vivir pronto', mid: 'A medio plazo' } },
        name: { t: '¿Cómo se llama?', ph: 'Nombre y apellidos' },
        email: { t: '¿A qué email le enviamos el dossier?', ph: 'su@email.com' },
        phone: { t: 'Por último, su teléfono', ph: 'Número de teléfono', hint: 'Un asesor le contactará por WhatsApp o llamada, en su idioma.' },
      },
      consent: 'Acepto la política de privacidad y el tratamiento de mis datos para recibir información sobre el proyecto.',
      errors: { name: 'Introduzca su nombre', email: 'Introduzca un email válido', phone: 'Introduzca un teléfono válido', consent: 'Debe aceptar la política de privacidad', server: 'No hemos podido enviar sus datos. Inténtelo de nuevo.' },
      done: {
        title: 'Gracias, su dossier está listo',
        text: 'Hemos recibido su solicitud. Un asesor de Fusión +34 le contactará en breve para resolver sus dudas y, si lo desea, organizar una videollamada o visita.',
        d1: 'Descargar dossier completo',
        d2: 'Descargar planos de venta',
        d3: 'Descargar memoria de calidades',
        close: 'Volver a la web',
      },
    },
  },

  en: {
    nav: { concept: 'Concept', villas: 'Villas', gallery: 'Gallery', location: 'Location', cta: 'Private brochure' },
    hero: {
      eyebrow: 'La Cala Golf · Mijas Costa · Costa del Sol',
      title1: 'Luxury Golf',
      title2: 'Collection',
      lead: '10 detached luxury villas with a private putting green, in the heart of La Cala Golf. Phase 1: only 5 homes.',
      cta: 'Get brochure & prices',
      cta2: 'Explore the villas',
      badge: 'Villa I · Final build phase',
      badgeSub: 'Visit the site in person',
      scroll: 'Discover',
    },
    stats: [
      { n: '10', l: 'Exclusive villas' },
      { n: '1,650', u: 'm²', l: 'Largest plot' },
      { n: '4', l: 'Bedrooms' },
      { n: '2', u: 'min', l: 'To La Cala Golf' },
      { n: '30', u: 'min', l: 'Málaga Airport' },
    ],
    concept: {
      eyebrow: 'A new residential paradigm',
      title: 'Not just a development. A privileged place to live.',
      text: 'An exclusive concept is born in the heart of La Cala Golf: a limited collection of 10 detached luxury villas on a private cul-de-sac with resident-only access. The Master Plan follows the natural topography, striking the perfect balance between community and absolute privacy.',
      features: [
        { t: 'Unrivalled views', d: 'North-South solar orientation for continuous natural light and panoramic views of the mountains and Mijas village.' },
        { t: 'Indoor · Outdoor', d: 'Covered and open terraces create a seamless flow between the home, the pool and the garden.' },
        { t: 'For golf lovers', d: 'Dedicated space to install a private putting green of approximately 50 m² on your own plot.' },
        { t: 'Your private resort', d: 'Private street, restricted access and generous plots: the feel of a resort with the intimacy of home.' },
      ],
    },
    finished: {
      eyebrow: 'Current status · A tangible investment',
      title: 'The first villa is already standing.',
      text: 'While other developments can only show renders, Villa I is in its final construction phase. You can visit the site, walk the plot, check the views and see the real materials before you decide — proof that the project is moving, with a fixed price from day one.',
      price: 'Villa I · Final build phase',
      priceNote: 'Sale price',
      facts: [
        ['Plot', '1,120 m²'],
        ['Built area', '280 m² + terraces'],
        ['Floors', '3 levels'],
        ['Bedrooms', '4 suites'],
        ['Garage', 'Double'],
        ['Pool', 'Infinity 11 × 3 m'],
      ],
      cta: 'Book a site visit',
    },
    villas: {
      eyebrow: 'Three typologies · One standard of excellence',
      title: 'Choose the villa that fits the way you live',
      text: 'Built with premium materials and high-end finishes, each property is a piece of contemporary architecture. Four Phase 1 villas are sold off-plan, with staged payments during construction.',
      items: [
        {
          id: 'villa-1', n: 'Villa I', name: 'The Beginning of Excellence', tag: 'Under construction', img: '/img/Contra_frente_III.jpg',
          specs: [['Plot', '1,120 m²'], ['Bedrooms', '4 suites'], ['Units', '1']],
          d: 'The first villa of the collection, currently under construction. It includes a multi-purpose room ideal for a private gym, cinema or games room, and is oriented to maximise the panoramic views, with dedicated space for a private putting green.',
          price: '€1,590,000',
        },
        {
          id: 'villa-2', n: 'Villa II', name: 'Family Design & Space', tag: 'Off-plan', img: '/img/Lateral_II.jpg',
          specs: [['Plot', '1,130 m²'], ['Beds / Baths', '4 / 5'], ['Units', '2']],
          d: 'Two units available in Stage 1, with private access. Four bedrooms and five full bathrooms give every resident and guest their privacy, plus a large multi-purpose room that adapts to modern living.',
          price: null,
        },
        {
          id: 'villa-3', n: 'Villa III', name: 'The Mountain Retreat', tag: 'Off-plan', img: '/img/FachadaII.jpg',
          specs: [['Plot', '1,650 m²'], ['Beds / Baths', '4 / 5'], ['Units', '2']],
          d: 'Two of the most generous units in Stage 1, on the largest plot of the collection. Full mountain views, private access and dedicated space for a private putting green.',
          price: null,
        },
      ],
      priceOnRequest: 'Price on request',
      cardCta: 'View plans & price',
      units: 'Phase 1 · 5 villas',
    },
    gallery: {
      eyebrow: 'Designed for wellbeing',
      title: 'Spaces to live in, light you can feel',
      items: [
        { src: '/img/salon-b.jpg', c: 'Living room opening onto a panoramic terrace' },
        { src: '/img/cocina-madera.jpg', c: 'Open Schmidt kitchen with views of Mijas' },
        { src: '/img/Terraza.jpg', c: 'Covered terrace and private pool' },
        { src: '/img/Dormitorio.jpg', c: 'Master bedroom with terrace' },
        { src: '/img/Vestidor_II.jpg', c: 'En-suite dressing room' },
        { src: '/img/Gimnasio.jpg', c: 'Flex room: private gym' },
        { src: '/img/Estar.jpg', c: 'Living-dining room opening to the terrace' },
        { src: '/img/salon-a.jpg', c: 'Lounge area' },
      ],
      disclaimer: 'Digitally recreated images, not contractually binding. Furniture and decoration not included.',
    },
    floors: {
      eyebrow: 'Three floors, endless possibilities',
      items: [
        { t: 'First floor', d: 'En-suite master bedroom with dressing room, two further bedrooms, full bathroom and private terraces.' },
        { t: 'Ground floor', d: 'Open-plan living-dining room, Schmidt kitchen with central island, guest toilet, terraces, semi-covered chill-out area, barbecue and an 11 × 3 m infinity pool.' },
        { t: 'Basement', d: 'Double garage with an electric-vehicle charging point, large naturally lit open space with a full bathroom (gym, cinema or 4th bedroom), laundry, technical room and lift pre-installation.' },
      ],
    },
    video: {
      line: 'Imagine waking up each morning in your private sanctuary, where luxury meets serenity.',
      sub: 'Flyover · La Cala Golf',
    },
    location: {
      eyebrow: 'Cala Golf · Costa del Sol',
      title: 'Your oasis of tranquillity in the heart of the Costa del Sol',
      text: 'La Cala Golf is much more than a prestigious residential area: it is a lifestyle blending tranquillity, luxury and nature. Five minutes from the motorway, halfway between Málaga and Marbella, with 320 days of sunshine and a well-established international community.',
      groups: [
        { t: 'Golf', items: [['La Cala Golf', '2 min'], ['Mijas Golf', '14 min'], ['Santana Golf', '19 min']] },
        { t: 'Coast', items: [['La Cala de Mijas', '11 min'], ['Marbella', '20 min'], ['Fuengirola', '24 min']] },
        { t: 'Everyday', items: [['Supermarkets', '8 min'], ['Pharmacy', '12 min'], ['Hospital', '12 min']] },
        { t: 'Connections', items: [['Málaga · High-speed rail · Airport', '30 min'], ['Gibraltar', '90 min']] },
      ],
      golf: {
        eyebrow: 'Two minutes away',
        t: 'One of the Costa del Sol’s most important golf courses, two minutes from your door',
        d: 'La Cala Golf is practically around the corner — a two-minute drive. An internationally recognised course that sets the tone for the whole area, and one you can extend into your own plot with a private putting green of around 50 m².',
      },
      map: {
        t: 'Getting here',
        d: 'Calle Lagar de La Cala Golf · La Cala Golf, Mijas Costa (Málaga)',
        cta: 'Open in Google Maps',
      },
    },
    quality: {
      eyebrow: 'Quality specifications',
      title: 'Quality you can verify, not just a promise',
      items: [
        'Underfloor heating throughout, zone by zone',
        'Mitsubishi aerothermal system for climate control and hot water',
        'Ducted air conditioning with Airzone zoning',
        'Schmidt kitchen with integrated central island',
        'Integrated Bosch appliances',
        'Cristacer Lloret Beige 90 × 90 rectified porcelain flooring',
        'Porcelanosa bathroom tiling and sanitaryware',
        'Strugal exterior joinery with thermal break',
        'Double glazing with air chamber and UV protection',
        'Frameless 8+8 laminated glass balustrades',
        'Infinity pool, 11 × 3 m, with overflow tank',
        'Video entry, alarm and zoned climate control',
        'Electric vehicle charging point',
        'Lift pre-installation across all three floors',
      ],
      more: 'Download the full specifications',
    },
    gated: {
      eyebrow: 'Private access',
      title: 'Everything you need, in one brochure',
      text: 'Answer 3 quick questions and instantly receive the full project documentation. An advisor will contact you in your language to answer any questions, with no obligation.',
      items: [
        ['Full brochure', 'Renders, layout and surroundings'],
        ['Sales floor plans', 'All three typologies with areas'],
        ['Quality specifications', 'Finishes and technical details'],
        ['Prices & payment plan', 'Updated Phase 1 availability'],
      ],
      cta: 'Unlock the brochure',
      time: 'Takes under 30 seconds',
    },
    process: {
      eyebrow: 'Buying from abroad, without surprises',
      title: 'A clear process, supported every step of the way',
      steps: [
        { t: 'Private video call', d: 'Review plans, views, prices and payment plan from home.' },
        { t: 'Visit the Costa del Sol', d: 'Walk through the completed villa, the plot and La Cala Golf.' },
        { t: 'Reservation & due diligence', d: 'Clear documentation, coordinated with your lawyer or tax advisor.' },
        { t: 'Construction & handover', d: 'Milestone payments and regular reports with photos and video.' },
      ],
    },
    final: {
      title: 'Make your Costa del Sol life a reality',
      text: 'Only 5 villas in Phase 1. Get the private brochure today and book your viewing.',
      cta: 'Send me the brochure',
    },
    footer: {
      promoted: 'Promueve · Promoted by',
      legal: 'Legal notice', privacy: 'Privacy policy', cookies: 'Cookie policy',
      disclaimer: 'All images are virtual recreations and not contractually binding. Furniture, vegetation and vehicles are not part of the offer. The developer Fusión +34 by Alternativa Málaga reserves the right to make modifications for technical, commercial or legal reasons, without any reduction in quality. Areas are approximate.',
    },
    sticky: 'Brochure & prices',
    wizard: {
      close: 'Close',
      back: 'Back',
      next: 'Continue',
      submit: 'Get the brochure',
      sending: 'Sending…',
      step: 'Step',
      of: 'of',
      intro: 'Private brochure · Luxury Golf Collection',
      q: {
        budget: { t: 'What is your approximate budget?', o: { lt1: 'Under €1M', '1to15': '€1M – €1.5M', gt15: 'Over €1.5M' } },
        location: { t: 'Are you currently on the Costa del Sol?', o: { yes: 'Yes, I’m here', no: 'No', soon: 'I plan to visit soon' } },
        timing: { t: 'Are you looking to move in soon or in the medium term?', o: { soon: 'To move in soon', mid: 'Medium term' } },
        name: { t: 'What is your name?', ph: 'Full name' },
        email: { t: 'Where should we send the brochure?', ph: 'you@email.com' },
        phone: { t: 'Finally, your phone number', ph: 'Phone number', hint: 'An advisor will reach you by WhatsApp or call, in your language.' },
      },
      consent: 'I accept the privacy policy and the processing of my data to receive information about the project.',
      errors: { name: 'Please enter your name', email: 'Please enter a valid email', phone: 'Please enter a valid phone number', consent: 'Please accept the privacy policy', server: 'We could not send your details. Please try again.' },
      done: {
        title: 'Thank you, your brochure is ready',
        text: 'We have received your request. A Fusión +34 advisor will contact you shortly to answer your questions and, if you wish, arrange a video call or viewing.',
        d1: 'Download full brochure',
        d2: 'Download sales floor plans',
        d3: 'Download the quality specifications',
        close: 'Back to the website',
      },
    },
  },
}

// Valores que se envían al CRM (siempre en español, independientemente del idioma de la web)
export const crmLabels = {
  budget: { lt1: 'Menos de 1M €', '1to15': '1M – 1,5M €', gt15: '+1,5M €' },
  location: { yes: 'En Costa del Sol', no: 'Fuera de Costa del Sol', soon: 'Visitará pronto' },
  timing: { soon: 'Vivir pronto', mid: 'Medio plazo' },
}
